# Generated by Django 5.2.7 on 2025-10-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0002_alter_user_email_alter_user_role_alter_user_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.DeleteModel(
            name='DoctorProfile',
        ),
    ]
