# Generated by Django 5.2.7 on 2025-11-09 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0002_alter_prescription_doctor_alter_prescription_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='user',
        ),
    ]
