# Generated by Django 5.2.7 on 2025-11-13 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0004_patientprofile_user_alter_prescription_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='Portion',
            new_name='portion',
        ),
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'role_SU_Doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
