# Generated by Django 5.2.7 on 2025-12-16 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0005_rename_portion_prescription_portion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='gender',
        ),
    ]
