# Generated by Django 5.2.7 on 2025-12-16 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0006_remove_patientprofile_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientProfile',
        ),
    ]
