# Generated by Django 5.2.7 on 2025-12-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0008_rename_prescription_date_prescription_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('PATIENT', 'Patient'), ('PHARMACIST', 'Pharmacist')], max_length=10, null=True),
        ),
    ]
