# Generated by Django 5.2.7 on 2025-12-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0010_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('DOCTOR', 'Doctor'), ('PATIENT', 'Patient'), ('PHARMACIST', 'Pharmacist')], max_length=10, null=True),
        ),
    ]
